/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BondingCurveInterface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "basePrice" | "buy" | "getBuyCost" | "getPrice" | "getSellRefund" | "market" | "sell" | "slope" | "totalRaised" | "totalSupply"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SharesBought" | "SharesSold"): EventFragment;

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'basePrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBuyCost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSellRefund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'market', values?: undefined): string;
encodeFunctionData(functionFragment: 'sell', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'slope', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRaised', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'basePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuyCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSellRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'market', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slope', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRaised', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
  }

  
    export namespace SharesBoughtEvent {
      export type InputTuple = [buyer: AddressLike, shares: BigNumberish, cost: BigNumberish];
      export type OutputTuple = [buyer: string, shares: bigint, cost: bigint];
      export interface OutputObject {buyer: string, shares: bigint, cost: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SharesSoldEvent {
      export type InputTuple = [seller: AddressLike, shares: BigNumberish, refund: BigNumberish];
      export type OutputTuple = [seller: string, shares: bigint, refund: bigint];
      export interface OutputObject {seller: string, shares: bigint, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BondingCurve extends BaseContract {
    
    connect(runner?: ContractRunner | null): BondingCurve;
    waitForDeployment(): Promise<this>;

    interface: BondingCurveInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    basePrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [buyer: AddressLike, shares: BigNumberish, cost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBuyCost: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPrice: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getSellRefund: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    market: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    sell: TypedContractMethod<
      [seller: AddressLike, shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    slope: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRaised: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'basePrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [buyer: AddressLike, shares: BigNumberish, cost: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBuyCost'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSellRefund'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'market'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [seller: AddressLike, shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slope'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRaised'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'SharesBought'): TypedContractEvent<SharesBoughtEvent.InputTuple, SharesBoughtEvent.OutputTuple, SharesBoughtEvent.OutputObject>;
getEvent(key: 'SharesSold'): TypedContractEvent<SharesSoldEvent.InputTuple, SharesSoldEvent.OutputTuple, SharesSoldEvent.OutputObject>;

    filters: {
      
      'SharesBought(address,uint256,uint256)': TypedContractEvent<SharesBoughtEvent.InputTuple, SharesBoughtEvent.OutputTuple, SharesBoughtEvent.OutputObject>;
      SharesBought: TypedContractEvent<SharesBoughtEvent.InputTuple, SharesBoughtEvent.OutputTuple, SharesBoughtEvent.OutputObject>;
    

      'SharesSold(address,uint256,uint256)': TypedContractEvent<SharesSoldEvent.InputTuple, SharesSoldEvent.OutputTuple, SharesSoldEvent.OutputObject>;
      SharesSold: TypedContractEvent<SharesSoldEvent.InputTuple, SharesSoldEvent.OutputTuple, SharesSoldEvent.OutputObject>;
    
    };
  }