/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MarketFactoryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "createMarket" | "getAllMarkets" | "getMarket" | "marketAdmin" | "token" | "transferAdmin"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarketCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'createMarket', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllMarkets', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMarket', values: [string]): string;
encodeFunctionData(functionFragment: 'marketAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
  }

  
    export namespace MarketCreatedEvent {
      export type InputTuple = [market: AddressLike, matchId: string, matchTime: BigNumberish];
      export type OutputTuple = [market: string, matchId: string, matchTime: bigint];
      export interface OutputObject {market: string, matchId: string, matchTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MarketFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): MarketFactory;
    waitForDeployment(): Promise<this>;

    interface: MarketFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createMarket: TypedContractMethod<
      [matchId: string, matchTime: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    getAllMarkets: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getMarket: TypedContractMethod<
      [matchId: string, ],
      [string],
      'view'
    >
    

    
    marketAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [matchId: string, matchTime: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllMarkets'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [matchId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'marketAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;

    filters: {
      
      'MarketCreated(address,string,uint256)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    
    };
  }