/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MatchMarketInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "buy" | "claim" | "claimed" | "curves" | "getMarketState" | "matchId" | "matchTime" | "resolve" | "resolved" | "resolvedOutcome" | "sell" | "token" | "totalPool"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarketResolved" | "WinnerClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'curves', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMarketState', values?: undefined): string;
encodeFunctionData(functionFragment: 'matchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'matchTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolve', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolved', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolvedOutcome', values?: undefined): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPool', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'curves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolvedOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPool', data: BytesLike): Result;
  }

  
    export namespace MarketResolvedEvent {
      export type InputTuple = [outcome: BigNumberish, totalPool: BigNumberish];
      export type OutputTuple = [outcome: bigint, totalPool: bigint];
      export interface OutputObject {outcome: bigint, totalPool: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinnerClaimedEvent {
      export type InputTuple = [winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [winner: string, amount: bigint];
      export interface OutputObject {winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MatchMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): MatchMarket;
    waitForDeployment(): Promise<this>;

    interface: MatchMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [outcome: BigNumberish, shares: BigNumberish, maxCost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    curves: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getMarketState: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {homePrice: bigint, homeSupply: bigint, drawPrice: bigint, drawSupply: bigint, awayPrice: bigint, awaySupply: bigint, isResolved: boolean, outcome: bigint }],
      'view'
    >
    

    
    matchId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    matchTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    resolve: TypedContractMethod<
      [outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolved: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    resolvedOutcome: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    sell: TypedContractMethod<
      [outcome: BigNumberish, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalPool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [outcome: BigNumberish, shares: BigNumberish, maxCost: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'curves'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketState'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {homePrice: bigint, homeSupply: bigint, drawPrice: bigint, drawSupply: bigint, awayPrice: bigint, awaySupply: bigint, isResolved: boolean, outcome: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'matchId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'matchTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolved'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'resolvedOutcome'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [outcome: BigNumberish, shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalPool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'WinnerClaimed'): TypedContractEvent<WinnerClaimedEvent.InputTuple, WinnerClaimedEvent.OutputTuple, WinnerClaimedEvent.OutputObject>;

    filters: {
      
      'MarketResolved(uint8,uint256)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'WinnerClaimed(address,uint256)': TypedContractEvent<WinnerClaimedEvent.InputTuple, WinnerClaimedEvent.OutputTuple, WinnerClaimedEvent.OutputObject>;
      WinnerClaimed: TypedContractEvent<WinnerClaimedEvent.InputTuple, WinnerClaimedEvent.OutputTuple, WinnerClaimedEvent.OutputObject>;
    
    };
  }