/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMatchMarket, IMatchMarketInterface } from "../../Resolver.sol/IMatchMarket.js";

  const _abi = [
  {
    "inputs": [],
    "name": "matchTime",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "outcome",
        "type": "uint8"
      }
    ],
    "name": "resolve",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMatchMarket__factory {
    static readonly abi = _abi;
    static createInterface(): IMatchMarketInterface {
      return new Interface(_abi) as IMatchMarketInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMatchMarket {
      return new Contract(address, _abi, runner) as unknown as IMatchMarket;
    }
  }
  