/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IMatchMarketInterface extends Interface {
    getFunction(nameOrSignature: "matchTime" | "resolve"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'matchTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolve', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'matchTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
  }

  

  export interface IMatchMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMatchMarket;
    waitForDeployment(): Promise<this>;

    interface: IMatchMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    matchTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    resolve: TypedContractMethod<
      [outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'matchTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }