/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ResolverInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "resolve" | "transferAdmin"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Resolved"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
  }

  
    export namespace ResolvedEvent {
      export type InputTuple = [market: AddressLike, outcome: BigNumberish];
      export type OutputTuple = [market: string, outcome: bigint];
      export interface OutputObject {market: string, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Resolver extends BaseContract {
    
    connect(runner?: ContractRunner | null): Resolver;
    waitForDeployment(): Promise<this>;

    interface: ResolverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolve: TypedContractMethod<
      [market: AddressLike, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [market: AddressLike, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Resolved'): TypedContractEvent<ResolvedEvent.InputTuple, ResolvedEvent.OutputTuple, ResolvedEvent.OutputObject>;

    filters: {
      
      'Resolved(address,uint8)': TypedContractEvent<ResolvedEvent.InputTuple, ResolvedEvent.OutputTuple, ResolvedEvent.OutputObject>;
      Resolved: TypedContractEvent<ResolvedEvent.InputTuple, ResolvedEvent.OutputTuple, ResolvedEvent.OutputObject>;
    
    };
  }